### ISSUE TITLE
The replica returned an HTTP Error

### ISSUE THREAD

**Issue by Techi-Dev** [dfinity/sdk#2187]
Im trying to run dfx locally and host, however the connection is crashing  with several errors and its not responsive, the code is right  which makes it to dictate and debug.

`The replica returned an HTTP Error: Http Error: status 500 Internal Server Error, content type "", content: Internal Server Error`

`Error: The post-build step failed for canister 'ryjl3-tyaaa-aaaaa-aaaba-cai' with an embedded error: The command '"npm" "run" "build"' failed with exit status 'exit status: 127'.`

what is your solution for this error?

**Comment by DrongLMM** [comment]
Decryption complete.
Redeeming coupon. This may take up to 30 seconds...
Error: Failed 'redeem' call.
Caused by: Failed 'redeem' call.
The replica returned a replica error: reject code CanisterReject, reject message Code is expired or not redeemable, error code None

#asking your help to solve the above problem?
