### ISSUE TITLE
Is it possible to run nodejs apps in a canister?

### ISSUE THREAD

**Issue by ralyodio** [dfinity/sdk#2203]
I’m trying to find out if there’s anyway to run a nodejs app inside a canister. 

We need ssr with sveltekit and the only way to do that is to have node run the client on port 443 using adapter-node

we would need nodemon to run the code so it restarts automatically if the app crashes. 

Is this possible?

**Comment by paulyoung** [comment]
I think the short answer is “no”, but you can write canisters in JavaScript and depend on NPM packages by using an experimental CDK called Azle: https://github.com/demergent-labs/azle

I doubt NodeJS APIs are going to work but @lastmjs can probably say more on that.

**Comment by lastmjs** [comment]
You can try Azle, but what you're describing is well beyond what Azle/canisters can do. Canisters do not use the traditional OS process architecture with that kind of behavior. You need to change your programming model.

What you can do is is npm install the SSR library and try to run it in Azle. If it works, you can use the `http_request` canister method to start piecing together a web server. You may run into issues with certain npm packages though. If you do, open issues with Azle so that the community can address them.

**Comment by krpeacock** [comment]
As far as I am concerned, @lastmjs has correctly answered this question. Closing this issue
